version: '3.7'

services:
  mongo:
    image: mongo:4
    restart: always
    restart: on-failure
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
  web:
    image: nginx
    ports:
      - '8080:80'

volumes:
  mongodb:
